name: C++ Compiler Workflow

on: 
  workflow_dispatch:

jobs:
  check-compiler-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ compiler (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        g++ --version

    - name: Set up C++ compiler (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw
        g++ --version

    - name: Compile example program (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        g++ -o hello hello.cpp
        ./hello

    - name: Compile example program (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        g++ -o hello.exe hello.cpp
        ./hello.exe
